export const products = [
    {
      id: 1,
      name: "Luxury Beachfront Villa",
      category: "Residential",
      price: 2000000,
      description: "A magnificent 5-bedroom villa with a private infinity pool and stunning ocean views.",
      imageUrl: "https://example.com/beachfront-villa.jpg",
      location: "Malibu, California",
      size: "6500 sqft",
      bedrooms: 5,
      bathrooms: 6,
      amenities: ["Private Pool", "Ocean View", "Smart Home", "Gym"],
      rating: 4.9,
      availability: "For Sale",
      listingAgent: {
        name: "Sophia Williams",
        contact: "sophia.williams@example.com",
        phone: "+1 123-456-7890",
      },
    },
    {
      id: 2,
      name: "Modern Loft Apartment",
      category: "Residential",
      price: 300000,
      description: "A sleek loft-style apartment with high ceilings, modern finishes, and city skyline views.",
      imageUrl: "https://example.com/loft-apartment.jpg",
      location: "San Francisco, California",
      size: "950 sqft",
      bedrooms: 1,
      bathrooms: 1,
      amenities: ["City Views", "Fitness Center", "Rooftop Access"],
      rating: 4.7,
      availability: "For Sale",
      listingAgent: {
        name: "Emma Brown",
        contact: "emma.brown@example.com",
        phone: "+1 987-654-3210",
      },
    },
    {
      id: 3,
      name: "Cozy Country Cottage",
      category: "Vacation",
      price: 450000,
      description: "A picturesque 3-bedroom cottage surrounded by rolling hills and serene countryside.",
      imageUrl: "https://example.com/country-cottage.jpg",
      location: "Charlottesville, Virginia",
      size: "1800 sqft",
      bedrooms: 3,
      bathrooms: 2,
      amenities: ["Fireplace", "Garden", "Proximity to Trails"],
      rating: 4.8,
      availability: "For Sale",
      listingAgent: {
        name: "Oliver Green",
        contact: "oliver.green@example.com",
        phone: "+1 123-987-6540",
      },
    },
    {
      id: 4,
      name: "Luxury Penthouse",
      category: "Residential",
      price: 3500000,
      description: "A lavish 4-bedroom penthouse with floor-to-ceiling windows and an expansive rooftop deck.",
      imageUrl: "https://example.com/penthouse.jpg",
      location: "New York City, New York",
      size: "4800 sqft",
      bedrooms: 4,
      bathrooms: 5,
      amenities: ["Private Elevator", "Rooftop Deck", "Concierge"],
      rating: 5.0,
      availability: "For Sale",
      listingAgent: {
        name: "James Wilson",
        contact: "james.wilson@example.com",
        phone: "+1 234-567-8901",
      },
    },
    {
      id: 5,
      name: "Charming Suburban Home",
      category: "Residential",
      price: 520000,
      description: "A charming 4-bedroom home in a quiet suburban neighborhood, perfect for families.",
      imageUrl: "https://example.com/suburban-home.jpg",
      location: "Plano, Texas",
      size: "2500 sqft",
      bedrooms: 4,
      bathrooms: 3,
      amenities: ["Backyard", "Garage", "Proximity to Schools"],
      rating: 4.5,
      availability: "For Sale",
      listingAgent: {
        name: "Emily Davis",
        contact: "emily.davis@example.com",
        phone: "+1 345-678-9102",
      },
    },
    {
      id: 6,
      name: "Historic Brownstone",
      category: "Residential",
      price: 1200000,
      description: "A beautifully restored 3-bedroom brownstone with original architectural details.",
      imageUrl: "https://example.com/brownstone.jpg",
      location: "Boston, Massachusetts",
      size: "3000 sqft",
      bedrooms: 3,
      bathrooms: 3,
      amenities: ["Fireplace", "Hardwood Floors", "Private Garden"],
      rating: 4.6,
      availability: "For Sale",
      listingAgent: {
        name: "Liam Martinez",
        contact: "liam.martinez@example.com",
        phone: "+1 678-910-1123",
      },
    },
    {
      id: 7,
      name: "Lakefront Cabin",
      category: "Vacation",
      price: 800000,
      description: "A tranquil cabin retreat overlooking a pristine lake, with fishing and boating access.",
      imageUrl: "https://example.com/lakefront-cabin.jpg",
      location: "Lake Tahoe, California",
      size: "2000 sqft",
      bedrooms: 4,
      bathrooms: 3,
      amenities: ["Deck", "Fire Pit", "Private Dock"],
      rating: 4.9,
      availability: "For Sale",
      listingAgent: {
        name: "Ava Johnson",
        contact: "ava.johnson@example.com",
        phone: "+1 456-789-0123",
      },
    },
    {
      id: 8,
      name: "Industrial Studio",
      category: "Residential",
      price: 250000,
      description: "A modern industrial-style studio apartment in a vibrant downtown area.",
      imageUrl: "https://example.com/industrial-studio.jpg",
      location: "Seattle, Washington",
      size: "750 sqft",
      bedrooms: 0,
      bathrooms: 1,
      amenities: ["Fitness Center", "Bike Storage", "Community Lounge"],
      rating: 4.2,
      availability: "For Sale",
      listingAgent: {
        name: "Mia Rivera",
        contact: "mia.rivera@example.com",
        phone: "+1 567-890-1234",
      },
    },
    {
        id: 9,
        name: "Contemporary Townhouse",
        category: "Residential",
        price: 670000,
        description: "A stylish 3-bedroom townhouse with a rooftop terrace and an open floor plan.",
        imageUrl: "https://example.com/contemporary-townhouse.jpg",
        location: "Denver, Colorado",
        size: "1800 sqft",
        bedrooms: 3,
        bathrooms: 3,
        amenities: ["Rooftop Terrace", "Garage", "Open Floor Plan"],
        rating: 4.7,
        availability: "For Sale",
        listingAgent: {
          name: "Lucas Taylor",
          contact: "lucas.taylor@example.com",
          phone: "+1 678-901-2345",
        },
      },
      {
        id: 10,
        name: "Urban Studio Apartment",
        category: "Residential",
        price: 220000,
        description: "A compact urban studio apartment in a highly walkable neighborhood.",
        imageUrl: "https://example.com/urban-studio.jpg",
        location: "Chicago, Illinois",
        size: "600 sqft",
        bedrooms: 0,
        bathrooms: 1,
        amenities: ["Walkable Area", "Secure Building", "Laundry Facilities"],
        rating: 4.3,
        availability: "For Sale",
        listingAgent: {
          name: "Zoe Clark",
          contact: "zoe.clark@example.com",
          phone: "+1 789-012-3456",
        },
      },
      {
        id: 11,
        name: "Seaside Vacation Home",
        category: "Vacation",
        price: 950000,
        description: "A beautiful 4-bedroom vacation home steps from the beach with breathtaking views.",
        imageUrl: "https://example.com/seaside-vacation-home.jpg",
        location: "Miami, Florida",
        size: "3200 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Beach Access", "Outdoor Patio", "Fully Furnished"],
        rating: 4.8,
        availability: "For Sale",
        listingAgent: {
          name: "Noah Hall",
          contact: "noah.hall@example.com",
          phone: "+1 890-123-4567",
        },
      },
      {
        id: 12,
        name: "Mountain Retreat",
        category: "Vacation",
        price: 650000,
        description: "A cozy 2-bedroom retreat nestled in the mountains, ideal for outdoor enthusiasts.",
        imageUrl: "https://example.com/mountain-retreat.jpg",
        location: "Jackson Hole, Wyoming",
        size: "1500 sqft",
        bedrooms: 2,
        bathrooms: 2,
        amenities: ["Fireplace", "Deck", "Proximity to Trails"],
        rating: 4.5,
        availability: "For Sale",
        listingAgent: {
          name: "Ella Carter",
          contact: "ella.carter@example.com",
          phone: "+1 901-234-5678",
        },
      },
      {
        id: 13,
        name: "Rustic Farmhouse",
        category: "Residential",
        price: 450000,
        description: "A charming 4-bedroom farmhouse surrounded by open fields and fresh air.",
        imageUrl: "https://example.com/rustic-farmhouse.jpg",
        location: "Nashville, Tennessee",
        size: "2800 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Porch", "Barn", "Land"],
        rating: 4.6,
        availability: "For Sale",
        listingAgent: {
          name: "Jack Miller",
          contact: "jack.miller@example.com",
          phone: "+1 123-345-6789",
        },
      },
      {
        id: 14,
        name: "Luxury Ski Chalet",
        category: "Vacation",
        price: 1800000,
        description: "An exquisite ski chalet with 5 bedrooms, hot tub, and ski-in/ski-out access.",
        imageUrl: "https://example.com/ski-chalet.jpg",
        location: "Aspen, Colorado",
        size: "5500 sqft",
        bedrooms: 5,
        bathrooms: 6,
        amenities: ["Hot Tub", "Ski Access", "Fireplace"],
        rating: 4.9,
        availability: "For Sale",
        listingAgent: {
          name: "Lily Moore",
          contact: "lily.moore@example.com",
          phone: "+1 234-456-7890",
        },
      },
      {
        id: 15,
        name: "Suburban Starter Home",
        category: "Residential",
        price: 300000,
        description: "A perfect starter home with 3 bedrooms, 2 bathrooms, and a fenced yard.",
        imageUrl: "https://example.com/starter-home.jpg",
        location: "Phoenix, Arizona",
        size: "1600 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Fenced Yard", "Garage", "Proximity to Schools"],
        rating: 4.4,
        availability: "For Sale",
        listingAgent: {
          name: "Hannah Harris",
          contact: "hannah.harris@example.com",
          phone: "+1 345-567-8901",
        },
      },
      {
        id: 16,
        name: "Penthouse in the Sky",
        category: "Residential",
        price: 2500000,
        description: "A breathtaking penthouse with panoramic city views and top-tier amenities.",
        imageUrl: "https://example.com/penthouse-sky.jpg",
        location: "Los Angeles, California",
        size: "4800 sqft",
        bedrooms: 3,
        bathrooms: 4,
        amenities: ["Pool", "Rooftop Deck", "Private Elevator"],
        rating: 5.0,
        availability: "For Sale",
        listingAgent: {
          name: "Ethan Wright",
          contact: "ethan.wright@example.com",
          phone: "+1 456-789-0123",
        },
      },
      {
        id: 17,
        name: "Downtown High-Rise Apartment",
        category: "Residential",
        price: 500000,
        description: "A stylish high-rise apartment in a bustling downtown area, with great city access.",
        imageUrl: "https://example.com/highrise-apartment.jpg",
        location: "Dallas, Texas",
        size: "1400 sqft",
        bedrooms: 2,
        bathrooms: 2,
        amenities: ["Fitness Center", "Parking Garage", "City Views"],
        rating: 4.3,
        availability: "For Sale",
        listingAgent: {
          name: "Grace Anderson",
          contact: "grace.anderson@example.com",
          phone: "+1 567-890-1234",
        },
      },
      {
        id: 18,
        name: "Cozy Lakeside Cottage",
        category: "Vacation",
        price: 400000,
        description: "A picturesque lakeside cottage with a dock and scenic surroundings.",
        imageUrl: "https://example.com/lakeside-cottage.jpg",
        location: "Lake Placid, New York",
        size: "1300 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Fireplace", "Lake Access", "Dock"],
        rating: 4.7,
        availability: "For Sale",
        listingAgent: {
          name: "Charlotte Baker",
          contact: "charlotte.baker@example.com",
          phone: "+1 678-901-2345",
        },
      },
      {
        id: 19,
        name: "Contemporary Duplex",
        category: "Residential",
        price: 620000,
        description: "A modern duplex with sleek finishes and an open-concept design.",
        imageUrl: "https://example.com/duplex.jpg",
        location: "Charlotte, North Carolina",
        size: "2100 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Garage", "Proximity to Shopping", "Private Patio"],
        rating: 4.5,
        availability: "For Sale",
        listingAgent: {
          name: "Matthew Scott",
          contact: "matthew.scott@example.com",
          phone: "+1 789-012-3456",
        },
      },
      {
        id: 20,
        name: "Private Island Villa",
        category: "Vacation",
        price: 8500000,
        description: "An exclusive private island villa with unparalleled privacy and oceanfront luxury.",
        imageUrl: "https://example.com/private-island-villa.jpg",
        location: "Key West, Florida",
        size: "12000 sqft",
        bedrooms: 8,
        bathrooms: 10,
        amenities: ["Private Beach", "Helipad", "Infinity Pool"],
        rating: 5.0,
        availability: "For Sale",
        listingAgent: {
          name: "Olivia Cooper",
          contact: "olivia.cooper@example.com",
          phone: "+1 890-123-4567",
        },
      },
    ];
    
  