export const products = [
    {
      id: 1,
      name: "Luxury Beachfront Villa",
      category: "Residential",
      price: 2000000,
      description: "A magnificent 5-bedroom villa with a private infinity pool and stunning ocean views.",
      imageUrl: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Malibu, California",
      size: "6500 sqft",
      bedrooms: 5,
      bathrooms: 6,
      amenities: ["Private Pool", "Ocean View", "Smart Home", "Gym"],
      rating: 4.9,
      availability: "For Sale",
      listingAgent: {
        name: "Sophia Williams",
        contact: "sophia.williams@example.com",
        phone: "+1 123-456-7890",
      },
    },
    {
      id: 2,
      name: "Modern Loft Apartment",
      category: "Residential",
      price: 300000,
      description: "A sleek loft-style apartment with high ceilings, modern finishes, and city skyline views.",
      imageUrl: "https://images.pexels.com/photos/87223/pexels-photo-87223.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "San Francisco, California",
      size: "950 sqft",
      bedrooms: 1,
      bathrooms: 1,
      amenities: ["City Views", "Fitness Center", "Rooftop Access"],
      rating: 4.7,
      availability: "For Sale",
      listingAgent: {
        name: "Emma Brown",
        contact: "emma.brown@example.com",
        phone: "+1 987-654-3210",
      },
    },
    {
      id: 3,
      name: "Cozy Country Cottage",
      category: "Vacation",
      price: 450000,
      description: "A picturesque 3-bedroom cottage surrounded by rolling hills and serene countryside.",
      imageUrl: "https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Charlottesville, Virginia",
      size: "1800 sqft",
      bedrooms: 3,
      bathrooms: 2,
      amenities: ["Fireplace", "Garden", "Proximity to Trails"],
      rating: 4.8,
      availability: "For Sale",
      listingAgent: {
        name: "Oliver Green",
        contact: "oliver.green@example.com",
        phone: "+1 123-987-6540",
      },
    },
    {
      id: 4,
      name: "Luxury Penthouse",
      category: "Residential",
      price: 3500000,
      description: "A lavish 4-bedroom penthouse with floor-to-ceiling windows and an expansive rooftop deck.",
      imageUrl: "https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "New York City, New York",
      size: "4800 sqft",
      bedrooms: 4,
      bathrooms: 5,
      amenities: ["Private Elevator", "Rooftop Deck", "Concierge"],
      rating: 5.0,
      availability: "For Sale",
      listingAgent: {
        name: "James Wilson",
        contact: "james.wilson@example.com",
        phone: "+1 234-567-8901",
      },
    },
    {
      id: 5,
      name: "Charming Suburban Home",
      category: "Residential",
      price: 520000,
      description: "A charming 4-bedroom home in a quiet suburban neighborhood, perfect for families.",
      imageUrl: "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Plano, Texas",
      size: "2500 sqft",
      bedrooms: 4,
      bathrooms: 3,
      amenities: ["Backyard", "Garage", "Proximity to Schools"],
      rating: 4.5,
      availability: "For Sale",
      listingAgent: {
        name: "Emily Davis",
        contact: "emily.davis@example.com",
        phone: "+1 345-678-9102",
      },
    },
    {
      id: 6,
      name: "Historic Brownstone",
      category: "Residential",
      price: 1200000,
      description: "A beautifully restored 3-bedroom brownstone with original architectural details.",
      imageUrl: "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Boston, Massachusetts",
      size: "3000 sqft",
      bedrooms: 3,
      bathrooms: 3,
      amenities: ["Fireplace", "Hardwood Floors", "Private Garden"],
      rating: 4.6,
      availability: "For Sale",
      listingAgent: {
        name: "Liam Martinez",
        contact: "liam.martinez@example.com",
        phone: "+1 678-910-1123",
      },
    },
    {
      id: 7,
      name: "Lakefront Cabin",
      category: "Vacation",
      price: 800000,
      description: "A tranquil cabin retreat overlooking a pristine lake, with fishing and boating access.",
      imageUrl: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Lake Tahoe, California",
      size: "2000 sqft",
      bedrooms: 4,
      bathrooms: 3,
      amenities: ["Deck", "Fire Pit", "Private Dock"],
      rating: 4.9,
      availability: "For Sale",
      listingAgent: {
        name: "Ava Johnson",
        contact: "ava.johnson@example.com",
        phone: "+1 456-789-0123",
      },
    },
    {
      id: 8,
      name: "Industrial Studio",
      category: "Residential",
      price: 250000,
      description: "A modern industrial-style studio apartment in a vibrant downtown area.",
      imageUrl: "https://images.pexels.com/photos/53610/large-home-residential-house-architecture-53610.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Seattle, Washington",
      size: "750 sqft",
      bedrooms: 0,
      bathrooms: 1,
      amenities: ["Fitness Center", "Bike Storage", "Community Lounge"],
      rating: 4.2,
      availability: "For Sale",
      listingAgent: {
        name: "Mia Rivera",
        contact: "mia.rivera@example.com",
        phone: "+1 567-890-1234",
      },
    },
    {
        id: 9,
        name: "Contemporary Townhouse",
        category: "Residential",
        price: 670000,
        description: "A stylish 3-bedroom townhouse with a rooftop terrace and an open floor plan.",
        imageUrl: "https://images.pexels.com/photos/36362/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Denver, Colorado",
        size: "1800 sqft",
        bedrooms: 3,
        bathrooms: 3,
        amenities: ["Rooftop Terrace", "Garage", "Open Floor Plan"],
        rating: 4.7,
        availability: "For Sale",
        listingAgent: {
          name: "Lucas Taylor",
          contact: "lucas.taylor@example.com",
          phone: "+1 678-901-2345",
        },
      },
      {
        id: 10,
        name: "Urban Studio Apartment",
        category: "Residential",
        price: 220000,
        description: "A compact urban studio apartment in a highly walkable neighborhood.",
        imageUrl: "https://images.pexels.com/photos/209296/pexels-photo-209296.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Chicago, Illinois",
        size: "600 sqft",
        bedrooms: 0,
        bathrooms: 1,
        amenities: ["Walkable Area", "Secure Building", "Laundry Facilities"],
        rating: 4.3,
        availability: "For Sale",
        listingAgent: {
          name: "Zoe Clark",
          contact: "zoe.clark@example.com",
          phone: "+1 789-012-3456",
        },
      },
      {
        id: 11,
        name: "Seaside Vacation Home",
        category: "Vacation",
        price: 950000,
        description: "A beautiful 4-bedroom vacation home steps from the beach with breathtaking views.",
        imageUrl: "https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Miami, Florida",
        size: "3200 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Beach Access", "Outdoor Patio", "Fully Furnished"],
        rating: 4.8,
        availability: "For Sale",
        listingAgent: {
          name: "Noah Hall",
          contact: "noah.hall@example.com",
          phone: "+1 890-123-4567",
        },
      },
      {
        id: 12,
        name: "Mountain Retreat",
        category: "Vacation",
        price: 650000,
        description: "A cozy 2-bedroom retreat nestled in the mountains, ideal for outdoor enthusiasts.",
        imageUrl: "https://images.pexels.com/photos/1330753/pexels-photo-1330753.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Jackson Hole, Wyoming",
        size: "1500 sqft",
        bedrooms: 2,
        bathrooms: 2,
        amenities: ["Fireplace", "Deck", "Proximity to Trails"],
        rating: 4.5,
        availability: "For Sale",
        listingAgent: {
          name: "Ella Carter",
          contact: "ella.carter@example.com",
          phone: "+1 901-234-5678",
        },
      },
      {
        id: 13,
        name: "Rustic Farmhouse",
        category: "Residential",
        price: 450000,
        description: "A charming 4-bedroom farmhouse surrounded by open fields and fresh air.",
        imageUrl: "https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800",
        location: "Nashville, Tennessee",
        size: "2800 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Porch", "Barn", "Land"],
        rating: 4.6,
        availability: "For Sale",
        listingAgent: {
          name: "Jack Miller",
          contact: "jack.miller@example.com",
          phone: "+1 123-345-6789",
        },
      },
      {
        id: 14,
        name: "Ikoyi Farmhouse",
        category: "Vacation",
        price: 1800000,
        description: "An exquisite ski chalet with 5 bedrooms, hot tub, and ski-in/ski-out access.",
        imageUrl: "https://images.pexels.com/photos/1438834/pexels-photo-1438834.jpeg?auto=compress&cs=tinysrgb&w=800",
        location: "Aspen, Colorado",
        size: "5500 sqft",
        bedrooms: 5,
        bathrooms: 6,
        amenities: ["Hot Tub", "Ski Access", "Fireplace"],
        rating: 4.9,
        availability: "For Sale",
        listingAgent: {
          name: "Lily Moore",
          contact: "lily.moore@example.com",
          phone: "+1 234-456-7890",
        },
      },
      {
        id: 15,
        name: "Suburban Starter Home",
        category: "Residential",
        price: 300000,
        description: "A perfect starter home with 3 bedrooms, 2 bathrooms, and a fenced yard.",
        imageUrl: "https://images.pexels.com/photos/8082319/pexels-photo-8082319.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Phoenix, Arizona",
        size: "1600 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Fenced Yard", "Garage", "Proximity to Schools"],
        rating: 4.4,
        availability: "For Sale",
        listingAgent: {
          name: "Hannah Harris",
          contact: "hannah.harris@example.com",
          phone: "+1 345-567-8901",
        },
      },
      {
        id: 16,
        name: "Penthouse in the Sky",
        category: "Residential",
        price: 2500000,
        description: "A breathtaking penthouse with panoramic city views and top-tier amenities.",
        imageUrl: "https://images.pexels.com/photos/8082319/pexels-photo-8082319.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Los Angeles, California",
        size: "4800 sqft",
        bedrooms: 3,
        bathrooms: 4,
        amenities: ["Pool", "Rooftop Deck", "Private Elevator"],
        rating: 5.0,
        availability: "For Sale",
        listingAgent: {
          name: "Ethan Wright",
          contact: "ethan.wright@example.com",
          phone: "+1 456-789-0123",
        },
      },
      {
        id: 17,
        name: "Downtown High-Rise Apartment",
        category: "Residential",
        price: 500000,
        description: "A stylish high-rise apartment in a bustling downtown area, with great city access.",
        imageUrl: "https://images.pexels.com/photos/8082328/pexels-photo-8082328.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Dallas, Texas",
        size: "1400 sqft",
        bedrooms: 2,
        bathrooms: 2,
        amenities: ["Fitness Center", "Parking Garage", "City Views"],
        rating: 4.3,
        availability: "For Sale",
        listingAgent: {
          name: "Grace Anderson",
          contact: "grace.anderson@example.com",
          phone: "+1 567-890-1234",
        },
      },
      {
        id: 18,
        name: "Cozy Lakeside Cottage",
        category: "Vacation",
        price: 400000,
        description: "A picturesque lakeside cottage with a dock and scenic surroundings.",
        imageUrl: "https://images.pexels.com/photos/18808734/pexels-photo-18808734/free-photo-of-large-mansion-with-orange-roof.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Lake Placid, New York",
        size: "1300 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Fireplace", "Lake Access", "Dock"],
        rating: 4.7,
        availability: "For Sale",
        listingAgent: {
          name: "Charlotte Baker",
          contact: "charlotte.baker@example.com",
          phone: "+1 678-901-2345",
        },
      },
      {
        id: 19,
        name: "Contemporary Duplex",
        category: "Residential",
        price: 620000,
        description: "A modern duplex with sleek finishes and an open-concept design.",
        imageUrl: "https://images.pexels.com/photos/28449020/pexels-photo-28449020/free-photo-of-modern-luxury-villa-aerial-view-with-pool.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Charlotte, North Carolina",
        size: "2100 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Garage", "Proximity to Shopping", "Private Patio"],
        rating: 4.5,
        availability: "For Sale",
        listingAgent: {
          name: "Matthew Scott",
          contact: "matthew.scott@example.com",
          phone: "+1 789-012-3456",
        },
      },
      {
        id: 20,
        name: "Private Island Villa",
        category: "Vacation",
        price: 8500000,
        description: "An exclusive private island villa with unparalleled privacy and oceanfront luxury.",
        imageUrl: "https://images.pexels.com/photos/7501130/pexels-photo-7501130.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Key West, Florida",
        size: "12000 sqft",
        bedrooms: 8,
        bathrooms: 10,
        amenities: ["Private Beach", "Helipad", "Infinity Pool"],
        rating: 5.0,
        availability: "For Sale",
        listingAgent: {
          name: "Olivia Cooper",
          contact: "olivia.cooper@example.com",
          phone: "+1 890-123-4567",
        },
      },
      {
        id: 21,
        name: "Eco-Friendly Tiny Home",
        category: "Residential",
        price: 85000,
        description: "A compact and sustainable 1-bedroom tiny home built with eco-conscious materials.",
        imageUrl: "https://images.pexels.com/photos/8082322/pexels-photo-8082322.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Portland, Oregon",
        size: "500 sqft",
        bedrooms: 1,
        bathrooms: 1,
        amenities: ["Solar Panels", "Smart Technology", "Energy-Efficient"],
        rating: 4.6,
        availability: "For Sale",
        listingAgent: {
            name: "Alex White",
            contact: "alex.white@example.com",
            phone: "+1 123-678-9100",
        },
    },
    {
        id: 22,
        name: "Beachside Condo",
        category: "Vacation",
        price: 750000,
        description: "A beachfront 2-bedroom condo with gorgeous sunrise views.",
        imageUrl: "https://images.pexels.com/photos/20427358/pexels-photo-20427358/free-photo-of-villa-with-palm-tree.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "San Diego, California",
        size: "1400 sqft",
        bedrooms: 2,
        bathrooms: 2,
        amenities: ["Balcony", "Beach Access", "Secure Parking"],
        rating: 4.8,
        availability: "For Sale",
        listingAgent: {
            name: "Sophia Bennett",
            contact: "sophia.bennett@example.com",
            phone: "+1 987-345-6712",
        },
    },
    {
        id: 23,
        name: "Modern Farmhouse",
        category: "Residential",
        price: 550000,
        description: "A 3-bedroom farmhouse with a modern touch, surrounded by nature.",
        imageUrl: "https://images.pexels.com/photos/15267020/pexels-photo-15267020/free-photo-of-facade-of-a-modern-architectural-design-of-a-residential-house.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Austin, Texas",
        size: "2800 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Open Layout", "Garage", "Porch"],
        rating: 4.5,
        availability: "For Sale",
        listingAgent: {
            name: "Daniel Carter",
            contact: "daniel.carter@example.com",
            phone: "+1 890-123-4321",
        },
    },
    {
        id: 24,
        name: "Luxury Treehouse",
        category: "Vacation",
        price: 400000,
        description: "A luxurious 1-bedroom treehouse nestled in a tropical rainforest.",
        imageUrl: "https://images.pexels.com/photos/7061662/pexels-photo-7061662.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Maui, Hawaii",
        size: "800 sqft",
        bedrooms: 1,
        bathrooms: 1,
        amenities: ["Nature Views", "Privacy", "Outdoor Shower"],
        rating: 4.9,
        availability: "For Sale",
        listingAgent: {
            name: "Charlotte Jones",
            contact: "charlotte.jones@example.com",
            phone: "+1 789-234-5678",
        },
    },
    {
        id: 25,
        name: "Urban Family Home",
        category: "Residential",
        price: 600000,
        description: "A family-friendly home in an urban area with nearby parks and schools.",
        imageUrl: "https://images.pexels.com/photos/15368400/pexels-photo-15368400/free-photo-of-mansion-among-palms-by-the-river.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Houston, Texas",
        size: "2000 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Backyard", "Garage", "Child-Friendly"],
        rating: 4.4,
        availability: "For Sale",
        listingAgent: {
            name: "Ethan Lee",
            contact: "ethan.lee@example.com",
            phone: "+1 234-456-7893",
        },
    },
    {
        id: 26,
        name: "Mid-Century Modern Ranch",
        category: "Residential",
        price: 820000,
        description: "A stylish mid-century ranch home with plenty of space and light.",
        imageUrl: "https://images.pexels.com/photos/28697977/pexels-photo-28697977/free-photo-of-charming-lakeside-house-with-scenic-forest-view.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Palm Springs, California",
        size: "3200 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Pool", "Palm Trees", "Proximity to Shops"],
        rating: 4.7,
        availability: "For Sale",
        listingAgent: {
            name: "Mia Lewis",
            contact: "mia.lewis@example.com",
            phone: "+1 987-654-4321",
        },
    },
    {
        id: 27,
        name: "Coastal Retreat",
        category: "Vacation",
        price: 970000,
        description: "An elegant coastal property offering serenity and panoramic sea views.",
        imageUrl: "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Naples, Florida",
        size: "3600 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Ocean Views", "Private Beach Access", "Balcony"],
        rating: 4.8,
        availability: "For Sale",
        listingAgent: {
            name: "Lily Thomas",
            contact: "lily.thomas@example.com",
            phone: "+1 345-678-9103",
        },
    },
    {
      id: 28,
      name: "Rustic Mountain Cabin",
      category: "Vacation",
      price: 500000,
      description: "A cozy cabin in the mountains with breathtaking views and hiking trails nearby.",
      imageUrl: "https://images.pexels.com/photos/19075392/pexels-photo-19075392/free-photo-of-deckchairs-by-swimming-pool.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Aspen, Colorado",
      size: "1200 sqft",
      bedrooms: 2,
      bathrooms: 1,
      amenities: ["Fireplace", "Deck", "Scenic Views"],
      rating: 4.7,
      availability: "For Sale",
      listingAgent: {
          name: "Olivia Garcia",
          contact: "olivia.garcia@example.com",
          phone: "+1 234-567-8910",
      },
  },
  {
      id: 29,
      name: "Chic City Apartment",
      category: "Residential",
      price: 850000,
      description: "A modern apartment in the heart of downtown with skyline views.",
      imageUrl: "https://images.pexels.com/photos/13752348/pexels-photo-13752348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "New York City, New York",
      size: "1000 sqft",
      bedrooms: 2,
      bathrooms: 2,
      amenities: ["Rooftop Access", "Gym", "Concierge Service"],
      rating: 4.5,
      availability: "For Sale",
      listingAgent: {
          name: "Liam Martinez",
          contact: "liam.martinez@example.com",
            phone: "+1 345-678-9012",
        },
    },
    {
        id: 30,
        name: "Secluded Forest Retreat",
        category: "Vacation",
        price: 620000,
        description: "A private forest getaway featuring serene surroundings and wildlife views.",
        imageUrl: "https://images.pexels.com/photos/8134748/pexels-photo-8134748.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Bend, Oregon",
        size: "1500 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Hot Tub", "Outdoor Firepit", "Hiking Trails"],
        rating: 4.6,
        availability: "For Sale",
        listingAgent: {
            name: "Noah Taylor",
            contact: "noah.taylor@example.com",
            phone: "+1 456-789-0123",
        },
    },
    {
        id: 31,
        name: "Lakeside Cottage",
        category: "Vacation",
        price: 450000,
        description: "A charming cottage with direct lake access and a private dock.",
        imageUrl: "https://images.pexels.com/photos/237408/pexels-photo-237408.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Lake Tahoe, Nevada",
        size: "1100 sqft",
        bedrooms: 2,
        bathrooms: 1,
        amenities: ["Dock", "Canoe Included", "Fishing Access"],
        rating: 4.8,
        availability: "For Sale",
        listingAgent: {
          name: "Emma Wilson",
          contact: "emma.wilson@example.com",
          phone: "+1 567-890-1234",
      },
  },
  {
      id: 32,
      name: "Modern Suburban Home",
      category: "Residential",
      price: 680000,
      description: "A stylish suburban home with a spacious backyard and modern finishes.",
      imageUrl: "https://images.pexels.com/photos/12558900/pexels-photo-12558900.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Seattle, Washington",
      size: "2400 sqft",
      bedrooms: 4,
      bathrooms: 3,
      amenities: ["Backyard", "Garage", "Energy-Efficient Appliances"],
      rating: 4.4,
      availability: "For Sale",
      listingAgent: {
          name: "James Brown",
          contact: "james.brown@example.com",
          phone: "+1 678-901-2345",
      },
  },
  {
      id: 33,
      name: "Oceanfront Villa",
      category: "Vacation",
      price: 1500000,
      description: "A luxury villa on the beach with spectacular ocean views and private pool.",
      imageUrl: "https://images.pexels.com/photos/12720676/pexels-photo-12720676.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      location: "Malibu, California",
      size: "4000 sqft",
      bedrooms: 5,
      bathrooms: 4,
      amenities: ["Infinity Pool", "Private Beach", "Spa Room"],
      rating: 4.9,
      availability: "For Sale",
      listingAgent: {
        name: "Sophia Johnson",
        contact: "sophia.johnson@example.com",
        phone: "+1 789-012-3456",
    },
},
{
    id: 34,
    name: "Historic Brownstone",
    category: "Residential",
    price: 1250000,
    description: "A renovated brownstone with historic charm and modern upgrades.",
    imageUrl: "https://images.pexels.com/photos/13620069/pexels-photo-13620069.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    location: "Boston, Massachusetts",
    size: "3500 sqft",
    bedrooms: 5,
    bathrooms: 3,
    amenities: ["Exposed Brick", "Private Garden", "Wine Cellar"],
    rating: 4.7,
    availability: "For Sale",
    listingAgent: {
        name: "Lucas Moore",
        contact: "lucas.moore@example.com",
        phone: "+1 890-123-4567",
    },
},
{
    id: 35,
    name: "Desert Adobe Home",
    category: "Vacation",
    price: 720000,
    description: "An adobe-style home with desert landscaping and stargazing deck.",
    imageUrl: "https://images.pexels.com/photos/7031405/pexels-photo-7031405.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    location: "Santa Fe, New Mexico",
    size: "1800 sqft",
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Stargazing Deck", "Saltillo Tile Floors", "Outdoor Fireplace"],
    rating: 4.6,
    availability: "For Sale",
        listingAgent: {
            name: "Ava Davis",
            contact: "ava.davis@example.com",
            phone: "+1 901-234-5678",
        },
    },
    {
        id: 36,
        name: "Luxurious Penthouse Suite",
        category: "Residential",
        price: 3200000,
        description: "An exquisite penthouse with 360-degree city views and premium amenities.",
        imageUrl: "https://images.pexels.com/photos/5215201/pexels-photo-5215201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Los Angeles, California",
        size: "5000 sqft",
        bedrooms: 4,
        bathrooms: 4,
        amenities: ["Rooftop Terrace", "Smart Home Features", "Private Elevator"],
        rating: 4.9,
        availability: "For Sale",
        listingAgent: {
            name: "Isabella Green",
            contact: "isabella.green@example.com",
            phone: "+1 234-567-8901",
        },
    },
    {
        id: 37,
        name: "Contemporary Loft",
        category: "Residential",
        price: 670000,
        description: "A chic loft in a revitalized historic building with industrial accents.",
        imageUrl: "https://images.pexels.com/photos/20876778/pexels-photo-20876778/free-photo-of-tree-in-front-of-a-mansion-in-fall.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Chicago, Illinois",
        size: "1300 sqft",
        bedrooms: 1,
        bathrooms: 1,
        amenities: ["Open Floor Plan", "Exposed Beams", "City Proximity"],
        rating: 4.5,
        availability: "For Sale",
        listingAgent: {
            name: "William Taylor",
            contact: "william.taylor@example.com",
            phone: "+1 345-678-9012",
        },
    },
    {
        id: 38,
        name: "Modern Countryside Villa",
        category: "Vacation",
        price: 800000,
        description: "A stunning countryside villa offering peace and luxury.",
        imageUrl: "https://images.pexels.com/photos/10681890/pexels-photo-10681890.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Napa Valley, California",
        size: "3000 sqft",
        bedrooms: 4,
        bathrooms: 3,
        amenities: ["Vineyard Views", "Swimming Pool", "Outdoor Kitchen"],
        rating: 4.8,
        availability: "For Sale",
        listingAgent: {
            name: "Charlotte White",
            contact: "charlotte.white@example.com",
            phone: "+1 456-789-0123",
        },
    },
    {
        id: 39,
        name: "Eco-Luxury Retreat",
        category: "Vacation",
        price: 980000,
        description: "A sustainable eco-retreat built with green materials and technologies.",
        imageUrl: "https://images.pexels.com/photos/27626185/pexels-photo-27626185/free-photo-of-a-large-house-with-a-pool-and-a-view-of-the-mountains.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Sedona, Arizona",
        size: "2000 sqft",
        bedrooms: 3,
        bathrooms: 2,
        amenities: ["Solar Power", "Green Roof", "Organic Garden"],
        rating: 4.9,
        availability: "For Sale",
        listingAgent: {
            name: "Henry Parker",
            contact: "henry.parker@example.com",
            phone: "+1 567-890-1234",
        },
    },
    {
        id: 40,
        name: "Tiny Eco-House",
        category: "Residential",
        price: 95000,
        description: "A small, fully sustainable home with smart space-saving features.",
        imageUrl: "https://images.pexels.com/photos/6032280/pexels-photo-6032280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        location: "Boulder, Colorado",
        size: "400 sqft",
        bedrooms: 1,
        bathrooms: 1,
        amenities: ["Smart Design", "Solar Panels", "Compact Appliances"],
        rating: 4.5,
        availability: "For Sale",
        listingAgent: {
            name: "Elizabeth Harris",
            contact: "elizabeth.harris@example.com",
            phone: "+1 678-901-2345",
        },
    },
  ];
    
  