export const products = [
    {
      id: 1,
      name: "Luxury Beachfront Villa",
      category: "Residential",
      price: 2000000,
      description: "A magnificent 5-bedroom villa with a private infinity pool and stunning ocean views.",
      imageUrl: "https://example.com/beachfront-villa.jpg",
      location: "Malibu, California",
      size: "6500 sqft",
      bedrooms: 5,
      bathrooms: 6,
      amenities: ["Private Pool", "Ocean View", "Smart Home", "Gym"],
      rating: 4.9,
      availability: "For Sale",
      listingAgent: {
        name: "Sophia Williams",
        contact: "sophia.williams@example.com",
        phone: "+1 123-456-7890",
      },
    },
    {
      id: 2,
      name: "Modern Loft Apartment",
      category: "Residential",
      price: 300000,
      description: "A sleek loft-style apartment with high ceilings, modern finishes, and city skyline views.",
      imageUrl: "https://example.com/loft-apartment.jpg",
      location: "San Francisco, California",
      size: "950 sqft",
      bedrooms: 1,
      bathrooms: 1,
      amenities: ["City Views", "Fitness Center", "Rooftop Access"],
      rating: 4.7,
      availability: "For Sale",
      listingAgent: {
        name: "Emma Brown",
        contact: "emma.brown@example.com",
        phone: "+1 987-654-3210",
      },
    },
    {
      id: 3,
      name: "Cozy Country Cottage",
      category: "Vacation",
      price: 450000,
      description: "A picturesque 3-bedroom cottage surrounded by rolling hills and serene countryside.",
      imageUrl: "https://example.com/country-cottage.jpg",
      location: "Charlottesville, Virginia",
      size: "1800 sqft",
      bedrooms: 3,
      bathrooms: 2,
      amenities: ["Fireplace", "Garden", "Proximity to Trails"],
      rating: 4.8,
      availability: "For Sale",
      listingAgent: {
        name: "Oliver Green",
        contact: "oliver.green@example.com",
        phone: "+1 123-987-6540",
      },
    },
    {
      id: 4,
      name: "Luxury Penthouse",
      category: "Residential",
      price: 3500000,
      description: "A lavish 4-bedroom penthouse with floor-to-ceiling windows and an expansive rooftop deck.",
      imageUrl: "https://example.com/penthouse.jpg",
      location: "New York City, New York",
      size: "4800 sqft",
      bedrooms: 4,
      bathrooms: 5,
      amenities: ["Private Elevator", "Rooftop Deck", "Concierge"],
      rating: 5.0,
      availability: "For Sale",
      listingAgent: {
        name: "James Wilson",
        contact: "james.wilson@example.com",
        phone: "+1 234-567-8901",
      },
    }
]